### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by MatthisB** [grongor/knock#11]
Returning tuple from socket.getaddrinfo() too long using IPv6.

Working for IPv4 / IPv6:
```
        self.address_family, _, _, _, addrinfo = socket.getaddrinfo(
                host=args.host,
                port=None,
                flags=socket.AI_ADDRCONFIG
            )[0]
        
        self.ip_address = addrinfo[0]
```

**Comment by grongor** [comment]
Sorry for the delay, and thank you for the report and the solution :) It's fixed now via https://github.com/grongor/knock/pull/12
